New-PSUScript -Name "Basic Output.ps1" -Description "A script with basic output." -Path "Basic Output.ps1" 
New-PSUScript -Name "Complex Output.ps1" -Description "A script with complex output. " -Path "Complex Output.ps1" 
New-PSUScript -Name "Parameters.ps1" -Description "A script with parameters." -Path "Parameters.ps1" 
New-PSUScript -Name "Feedback.ps1" -Description "A script that requests feedback. " -Path "Feedback.ps1" 
New-PSUScript -Name "Dev Script.ps1" -Description "Dev Script.ps1" -Tag @('Dev') -Path "Dev Script.ps1"