New-PSUScript -Name "Basic Output.ps1" -Description "A script with basic output." -Path "Basic Output.ps1" 
New-PSUScript -Name "CacheValue.ps1" -Description "CacheValue.ps1" -Path "CacheValue.ps1" 
New-PSUScript -Name "Complex Output.ps1" -Description "A script with complex output. " -Path "Complex Output.ps1" 
New-PSUScript -Name "Custom Module.ps1" -Description "Runs a function from a custom module. " -Path "Custom Module.ps1" 
New-PSUScript -Name "Debug Script.ps1" -Description "Runs a script that includes a Wait-Debugger command. " -Path "Debug Script.ps1" 
New-PSUScript -Name "Dev Script.ps1" -Description "Dev Script.ps1" -Tag @('Dev') -Path "Dev Script.ps1" 
New-PSUScript -Name "Environment.ps1" -Description "Displays the environment that is running the script." -Path "Environment.ps1" 
New-PSUScript -Name "Failed Job.ps1" -Description "Script that is triggered when a job fails. " -Path "Failed Job.ps1" 
New-PSUScript -Name "Failure.ps1" -Description "A job that fails." -Path "Failure.ps1" 
New-PSUScript -Name "Feedback.ps1" -Description "A script that requests feedback. " -Path "Feedback.ps1" 
New-PSUScript -Name "Nested Script.ps1" -Description "This script is a part of a nested folder. " -Path "Nested Scripts\Nested Script.ps1" 
New-PSUScript -Name "Parameters.ps1" -Description "A script with parameters." -Path "Parameters.ps1" 
New-PSUScript -Name "Portal Script.ps1" -Description "A script that is assigned to a user in the portal." -Path "Portal Script.ps1" -Role @('Administrator') -PortalOutputType "Text" 
New-PSUScript -Name "Portal Table.ps1" -Description "A script that runs in the portal and displays a table." -Path "Portal Table.ps1" -Role @('Administrator') -PortalOutputType "Table" 
New-PSUScript -Name "Variables.ps1" -Description "A script that displays platform variables." -Path "Variables.ps1"